### PR TITLE
Update pco.yml

### PR DESCRIPTION
**Pull request by ramonawalls**
PCO release

### CODE REVIEW

**Comment by ramonawalls** [comment]
@jamesaoverton Did this fail due to issue #751? The only change I made was to add a new exact replacement for the latest version, which seems like something even I could get right.

**Comment by jamesaoverton** [comment]
Yes, the failure is not your fault. Your change looks fine. I'll test it locally and merge it as soon as I get a chance.

**Comment by ramonawalls** [comment]
Thanks @jamesaoverton .

**Comment by cmungall** [comment]
@ramonawalls you could do this the same way we do for many other ontologies, where there is no need to update the cfg with each release

See ODK and for example:
https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/pato.yml#L21-L22

**Pull request merged**
