### PR TITLE
Update ogms.yml

### PR DESCRIPTION
**Pull request by BAevermann**
Removed links to googlecode which were dead.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
PURLs are supposed to persist: we really don't like removing links to published versions of ontologies. Is there any way that these files can be moved to a new host, such as GitHub?

**Comment by jamesaoverton** [comment]
From this page you should be able to download all the OGMS source files from Google Code, or export it to a new GitHub repository:

https://code.google.com/archive/p/ogms/source/default/source

**Comment by BAevermann** [comment]
The repo was moved to Github a long time ago prior to my involvement. I do not know why they did not move all necessary versions, etc.. The purls currently listed in the yaml are all dead. I will investigate moving the previous releases to github and I guess we can just leave the links as they are if that is preferred.

Thanks,

Brian Aevermann

—
Brian Aevermann
Bioinformatics Analyst
J. Craig Venter Institute
4120 Capricorn Lane
La Jolla, CA 92037
858-200-1873

**Comment by jamesaoverton** [comment]
Thanks for that information. It looks like the old releases of OGMS are available on a GitHub branch called `releases` here: <https://github.com/OGMS/ogms/tree/releases>. I've updated `ogms.yml` to point to these. Can you please double check?

**Comment by zhengj2007** [comment]
@jamesaoverton The OGMS releases folder is empty. I found the files in the google project site. I will work with @BAevermann to add the released files in git repo to make all PURLs work.

**Comment by BAevermann** [comment]
Hey James,

Thanks for finding those releases. That is an unusual place for them to be, but I will maintain them as such so that the new PURLs will stable.

Thanks again!

Brian Aevermann


—
Brian Aevermann
Bioinformatics Analyst
J. Craig Venter Institute
4120 Capricorn Lane
La Jolla, CA 92037
858-200-1873

**Pull request merged**
