### PR TITLE
Update MF to reflect move from Google Code to GitHub

### PR DESCRIPTION
**Pull request by jannahastings**

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Hi @jannahastings: Let's try something different this time. Can you please update this pull request to match the `master` branch, then change your links to use `https`. I'll merge the updated pull request.

If you have any trouble, let me know, and I'll make my own PR. Sorry for the mess I made.

**Comment by jannahastings** [comment]
I think I did it can you check? What about the other 2 files do I have to do something there too?

**Comment by jamesaoverton** [comment]
The other two have already been merged and should be live.

This one has a duplicate entry that needs to be removed:

    - exact: /external/bfo-properties-slim.owl
      replacement: http://mental-functioning-ontology.googlecode.com/svn/trunk/ontology/external/bfo-properties-slim.owl		 +  replacement: https://raw.githubusercontent.com/jannahastings/mental-functioning-ontology/master/ontology/external/bfo-properties-slim.owl

**Comment by jannahastings** [comment]
OK, thanks!

**Pull request merged**
