### PR TITLE
Update zeco.yml

### PR DESCRIPTION
**Pull request by matentzn**
Enable generic fall-through redirect.

### CODE REVIEW

**Comment by althonos** [comment]
@matentzn : seems like you didn't rebuild the site, `zeco.md` still contains `zeco.obo` twice! http://www.obofoundry.org/ontology/zeco.html

**Comment by matentzn** [comment]
@althonos I cant do that; This pull request only made sure that

http://purl.obolibrary.org/obo/zeco.json

resolves correctly!

https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/zeco.md

determines what products are shown on the site. Changes on the life site only apply once Chris re-deploys the site at some point!

**Comment by althonos** [comment]
Bump @cmungall then :grin:

**Comment by jamesaoverton** [comment]
A change was required to [zeco.md](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/zeco.md), which I made in https://github.com/OBOFoundry/OBOFoundry.github.io/commit/c8d053bbe411479f643e647bba946730bd93e327. So this page should now be correct: http://www.obofoundry.org/ontology/zeco.html

**Comment by matentzn** [comment]
James life safer :P Ahhhh I am too hasty!

**Pull request merged**
