### PR TITLE
experiment: redirect to amigo

### PR DESCRIPTION
**Pull request by cmungall**
I suspect this will not work - amigo only works with CURIEs

### CODE REVIEW

**Comment by jamesaoverton** [comment]
You need to define the custom redirect in [`obo.yml`](https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/obo.yml#L49)

**Comment by cmungall** [comment]
Thanks! Will do.

**Comment by cmungall** [comment]
Aside: there is some confusion redundancy in some of the ymls; e.g. hp.yml has

```yaml
- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=HP&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/HP_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=HP&iri=http://purl.obolibrary.org/obo/HP_0000001
```

This is harmless but confusing, as it is over-ridden by the following in obo.yml

```
# Term redirects for HP
- regex: ^/obo/HP_(\d+)$
  replacement: https://hpo.jax.org/app/browse/term/HP:$1
  status: see other
  tests:
  - from: /HP_0002088
    to: https://hpo.jax.org/app/browse/term/HP:0002088
```

not a priority and likely noted elsewhere

**Comment by jamesaoverton** [comment]
Looking at the git blame, that chunk of hp.yml is from the original migration from OCLC XML dumps to our YAML.

**Review by jamesaoverton — APPROVED** [review]
This change looks right to me.

Currently someone (i.e. me) has to manually update the PURL server after merging.

Are you ready for me to make this update any time, or do you want to coordinate the change so you can monitor?

**Comment by cmungall** [comment]
I am OK for you to make the change any time but if you could notify @kltm and me after you do it on slack that would be great

**Pull request merged**
