### PR TITLE
Update pco.yml

### PR DESCRIPTION
**Pull request by ramonawalls**
Fix exact replacement to fix PopulationAndCommunityOntology/pco#84 and add prefix for latest release.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
I think you just want two new `exact` entries, one for the new 2020-08-26 release, and one for the 2020-02-13 problem that redirects it to 2020-02-12.

```
- exact: /releases/2020-08-26/pco.owl
   replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2020-08-26/pco.owl
# Handle typo in date, see https://github.com/PopulationAndCommunityOntology/pco/issues/84
- exact: /releases/2020-02-13/pco.owl
   replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2020-02-12/pco.owl
```

Does that sound right?

**Comment by ramonawalls** [comment]
My intention was to replace the exact entry with a prefix for the latest release, which should cover the purl for /releases/2020-08-26/pco.owl as well as everything else in that tag. I should probably change all the old ones too (except 2020-02-12, which is wonky), but I did not have time.

For the exact replacement for 202012-02, what I wrote works, even if it looks weird, because the github paths are what I expect, the mistake is just in the OWL file, which I can't change now. Hopefully, that version won't be needed much.

So, I _think_ what I wrote is correct.

**Comment by jamesaoverton** [comment]
I'm pretty sure this is what you want:

1. a `prefix` for releases
2. an `exact` for 2020-02-13 that points to 2020-02-12

Please confirm.

**Comment by ramonawalls** [comment]
Yes, exactly.
------------------------------------------------------
Ramona L. Walls, Ph.D.
Assistant Research Professor, Bio5 Institute, University of Arizona
Part-time artist (https://www.instagram.com/omnivoresgratitutude/)

**Comment by ramonawalls** [comment]
Yes, exactly. Thanks for taking the time to look at this.

**Pull request merged**
