### PR TITLE
Update fbbt.yml

### PR DESCRIPTION
**Pull request by dosumis**
Syntax error in previous pull request.  This corrects it.  Change needed urgently.

### CODE REVIEW

**Comment by dosumis** [comment]
Not clear to me why this is failing:

FAIL	/obo/fbbt/vfb/vfb.owl	302	http://virtualflybrain.org/owl/vfb.owl	302	

With the old Purl server system, it was possible to have an exact redirect under a partial.  Is this still the case?

**Comment by cmungall** [comment]
I'm at a meeting and James is on a plane.

It looks like James corrected the problem by having the `exact:` precede the `prefix:`. But this had a typo, David corrected this, but reintroduced the ordering issue (and a conflict).

I can try and look at this later I don't want to rush this and introduce further confusing. @dosumis perhaps just close this, make a new PR, with the desired URLs, but make the exact precede the prefix (I believe it's in order of priority for matching)

**Comment by jamesaoverton** [comment]
@dosumis: Is it working as expected now?

**Comment by dosumis** [comment]
> @dosumis: Is it working as expected now?

Yep.  That's perfect.  Thanks!

**Pull request closed without merging**
