### PR TITLE
Update dideo.yml

### PR DESCRIPTION
**Pull request by mbrochhausen**

### CODE REVIEW

**Comment by cmungall** [comment]
I recommend not checking releases into master. Why not use the GitHub release mechanism

Spaces in folder names is also generally a bad idea

**Comment by mbrochhausen** [comment]
Chris,

thanks, I will change the folder name.
Regarding the release mechanism is there an example of an OBO ontology doing that, so we can look into it?

Thanks,
Mathias

**Comment by cmungall** [comment]
Have a look at the ontology starter kit, described here: 
https://github.com/monarch-initiative/monarch-disease-ontology

Also

https://github.com/pato-ontology/pato/
https://github.com/oborel/obo-relations/
https://github.com/obophenotype/porifera-ontology
https://github.com/obophenotype/ctenophore-ontology

**Comment by mbrochhausen** [comment]
Thanks!

**Pull request merged**
