### PR TITLE
(MERGE on 2018-02-28) Updating go snapshot -> current

### PR DESCRIPTION
**Pull request by lpalbou**

### CODE REVIEW

**Comment by lpalbou** [comment]
@cmungall sure, it can wait until the end of month release to avoid any surprise.

 I didn't see any reference to go-basic or go-plus in that file however, are they automatically built from the canonic go PURL or is there another file ?

**Comment by cmungall** [comment]
Yes, we use a partial redirect to http://current.geneontology.org/ontology

**Comment by lpalbou** [comment]
@cmungall the release is out since march 10, could you merge this branch ? I don't have the sufficient rights to do it. Thanks !

**Comment by kltm** [comment]
This will currently time travel, although not a lot.

**Comment by cmungall** [comment]
Yes, that's why I'm inclined to wait for the next release, unless there is a need to switch it before

**Comment by kltm** [comment]
Assuming things go right on a current test, I'll be triggering a `release` run later this afternoon. Otherwise, the end of the month is nigh.

**Comment by cmungall** [comment]
Perfect, I'll merge tomorrow

**Comment by cmungall** [comment]
Linked tickets: https://github.com/geneontology/go-announcements/issues/18

**Comment by cmungall** [comment]
@kltm looks like Jenkins run was successful but don't see in http://release.geneontology.org/ yet, this last part a manual copy?

**Comment by kltm** [comment]
I will be "finalizing" the release now, but that is odd. I will check into it first.

**Comment by kltm** [comment]
Now, that "should" have already occurred.

**Comment by kltm** [comment]
http://release.geneontology.org/2019-03-18/ does indeed exist and current does seem to have the same thing and be correct.

**Comment by lpalbou** [comment]
@cmungall @kltm thanks !

**Pull request merged**
