### PR TITLE
Brain Data Standards Ontology url redirection

### PR DESCRIPTION
**Pull request by hkir-dev**
Configuration update request to support Brain Data Standards Ontology as part of the Cell Ontology. 

Two new PURLs added for BDS ontology home page (`/bds/`) and custom OLS (`/bds/browser/`) instance redirections.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
When a `prefix` ends with `/` we usually want the `replacement` to also end with a `/`. Is that the case here?

**Comment by hkir-dev** [comment]
Thank you for the feedback. Removed the trailing `/` from prefixes to match the replacements.

**Comment by jamesaoverton** [comment]
Sorry, I wasn't clear: We usually want both the prefix and the replacement to end with "/". I made a commit that does this. Is this ok?

**Review by hkir-dev — COMMENTED** [review]
Agree with this update.

**Comment by jamesaoverton** [comment]
@abessiari The automated checks for this PR passed, but when I ran `make all test` on the current production server I got this error:

```
The following idspaces encountered failures: CL.                                                                                                                                              
1 failure (path, expected, actual):                                                                                                                                                           
  /obo/cl/bds/browser/                                                                                                                                                                        
    302 http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:8080/ontologies/bds2/                                                                                                         
    302 https://github.com/obophenotype/brain_data_standards_ontologies/tree/workshop_dosdp_improvement/browser/  
```

That's correct: there was a problem with the cl.yml that I had to fix in #774. Any ideas why the GitHub Action said the tests passed?

**Comment by abessiari** [comment]
Bizarre. The "make all test" did run and the logs show "Checking cl.yml ...." with no errors. 
I will dig deeper and report back.

**Comment by abessiari** [comment]
Ok. My bad. 
Fixed in https://github.com/OBOFoundry/purl.obolibrary.org/pull/776.  Needed to mount a volume for docker test. 
@jamesaoverton please approve and merge.

**Pull request merged**
