### PR TITLE
Create hancestro.yml

### PR DESCRIPTION
**Pull request by daniwelter**
This is the proposed config file for the Human Ancestry Ontology (HANCESTRO) - previously known as ANCESTRO.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
I see the discussion of ANCESTRO on the OBO mailing list from April. Before adding this PURL entry, you need an OBO Registry entry in this repository: https://github.com/OBOFoundry/OBOFoundry.github.io

This PURL configuration file is good except that `products:` should only include `hancestro.owl`, not the other variants. The variants should be under `entries:` like this:

```
- exact: /hancestro_inferred.owl
  replacement: https://raw.githubusercontent.com/EBISPOT/ancestro/master/hancestro_inferred.owl

- exact: /hancestro_bfo.owl
  replacement: https://raw.githubusercontent.com/EBISPOT/ancestro/master/hancestro_bfo.owl
```

The first will then be available at <http://purl.obolibrary.org/obo/hancestro/hancestro_inferred.owl>.

**Comment by daniwelter** [comment]
Thank you for the comments. File now fixed.

Dani Welter, PhD
Ontologist/Bioinformatician
Samples, Phenotypes and Ontologies Team
---------------------------------------
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
Tel: +44 (0) 1223 492 502

**Comment by daniwelter** [comment]
Any update on when this might be merged?

**Comment by daniwelter** [comment]
Thanks for merging. I can see hancestro in the obo foundry and it's been picked up by OLS but the URIs don't resolved in Ontobee yet. Do I need to do anything additional for that to happen? I can't find any instructions anywhere.

**Comment by jamesaoverton** [comment]
Ontobee is run by a separate group. I'm not sure how or how often they add new ontologies.

I suggest contacting their Google Group: ontobee-discuss@googlegroups.com

**Comment by cmungall** [comment]
Also: https://github.com/OntoZoo/ontobee/issues

**Pull request merged**
