### PR TITLE
Create cio.yml

### PR DESCRIPTION
**Pull request by jamesaoverton**
See https://github.com/OBOFoundry/OBOFoundry.github.io/pull/262

### CODE REVIEW

**Comment by jamesaoverton** [comment]
See also https://github.com/OBOFoundry/OBOFoundry.github.io/issues/248

@fbastian: This Pull Request creates PURLs for the OWL and OBO files linked to on your project [home page](https://github.com/BgeeDB/confidence-information-ontology). When this PR is merged, they will appear at:

- http://purl.obolibrary.org/obo/cio.owl
- http://purl.obolibrary.org/obo/cio.obo

Do you want any other PURLs added at this time? (Please see the [README](https://github.com/OBOFoundry/purl.obolibrary.org) for a longer description, and feel free to ask any question. I'm at a conference, but I'll get back to you as soon as I can.

**Comment by fbastian** [comment]
Thanks! Maybe we could have a PURL to the cio-simple.obo version?

**Comment by jamesaoverton** [comment]
@fbastian: Is this what you want?

- http://purl.obolibrary.org/obo/cio.owl --> https://raw.githubusercontent.com/BgeeDB/confidence-information-ontology/master/src/ontology/cio.owl
-  http://purl.obolibrary.org/obo/cio.obo --> https://raw.githubusercontent.com/BgeeDB/confidence-information-ontology/master/src/ontology/cio.obo
- http://purl.obolibrary.org/obo/cio/cio-simple.obo --> https://raw.githubusercontent.com/BgeeDB/confidence-information-ontology/master/src/ontology/cio-simple.obo

**Comment by fbastian** [comment]
Yes, thank you.

**Pull request merged**
