### PR TITLE
Update omiabis.yml

### PR DESCRIPTION
**Pull request by mbrochhausen**
re-directed PURL

Question: Is the statement in line 68/69 redundant and should I delete that?

### CODE REVIEW

**Comment by jamesaoverton** [comment]
The `exact` entries are prefixed by the `base_url`, which is `/obo/omiabis` in this case. So `exact: /omiabis.owl` matches `http://purl.obolibrary.org/obo/ombiabis/omiabis.owl`. Is that what you want?

**Comment by mbrochhausen** [comment]
Yes. I am wondering whether that is redundant and I could just delete the
exact: /omiabis.owl.

**Comment by jamesaoverton** [comment]
You probably only want the `products` entry, which will match `http://purl.obolibrary.org/obo/omiabis.owl`.

**Comment by mbrochhausen** [comment]
thanks!

On Fri, May 20, 2016 at 10:29 AM, James A. Overton <notifications@github.com

**Comment by jamesaoverton** [comment]
I'm combining #198 and #199 into #200.

**Pull request closed without merging**
