### PR TITLE
Update uo.yml

### PR DESCRIPTION
**Pull request by reality**
Updated UO.yml pointers for new ODK repo setup

### CODE REVIEW

**Comment by reality** [comment]
unless i misunderstand, I think this would be handled by the following line included in the commit:

``` unit-ontology.owl: https://raw.githubusercontent.com/bio-ontology-research-group/unit-ontology/master/unit-ontology.owl ```

**Review by jamesaoverton — CHANGES_REQUESTED** [review]
Sorry, I did not see the initial notification for this PR for some reason.

Products must only use your official OBO namespace, so a `unit-ontology.owl` product is not allowed.

The UO project only has control to its official namespace at <http://purl.obolibrary.org/obo/uo/>, but the Version IRI I'm seeing for the new file uses a different namespace 'unit-ontology': <http://purl.obolibrary.org/obo/unit-ontology/releases/2023-05-23/unit-ontology.owl>.

**Comment by jamesaoverton** [comment]
https://github.com/bio-ontology-research-group/unit-ontology/issues/71

**Comment by reality** [comment]
IRI/namespaces etc have now been changed to UO as requested

**Review by jamesaoverton — APPROVED** [review]

**Comment by jamesaoverton** [comment]
Much appreciated!

**Pull request merged**
