### PR TITLE
Update duo.yml

### PR DESCRIPTION
**Pull request by mcourtot**
added link to csv file

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Hi @mcourtot. The `product` field is for a project's primary OWL file and OBO file, and occasionally a JSON representation of the ontology. Nobody has asked for a CSV `product` before.

Would it work for you as <http://purl.obolibrary.org/obo/duo/duo.csv> with the following entry?

```
- exact: duo.csv
  replacement: https://raw.githubusercontent.com/EBISPOT/DUO/master/duo.csv
```

**Comment by mcourtot** [comment]
happy either way - I'm just hoping for a system that allows to consistently point to the CSV file

Do you know if there is a way to version it as well?

**Comment by jamesaoverton** [comment]
You have a bunch of options for versioning, but I think the best options are already working without this PR: 

1. Because of your `prefix: /` PURL entry, you can already point to the master version of any file in the repository. For example <http://purl.obolibrary.org/obo/duo/duo.csv> already points to the `master` version <https://raw.githubusercontent.com/EBISPOT/DUO/master/duo.csv>
2. Because of your `prefix: /releases/` PURL entry, you can already access any release of any file in the repository. For example <http://purl.obolibrary.org/obo/duo/releases/2020-02-03/governance.md> points to <https://raw.githubusercontent.com/EBISPOT/DUO/v2020-02-03/governance.md>.

**Comment by jamesaoverton** [comment]
I think my comment addressed your requirements, so I'll close this PR. Feel free to reopen if needed.

**Pull request closed without merging**
