### PR TITLE
This PR has been superseded by PR 765

### PR DESCRIPTION
**Pull request by abessiari**
added a task to install s3cmd and a task to test s3 access to bucket using s3 ls.

Tested using EC2 instance.
ansible-playbook -i "18.236.75.XXX," site.yml
ansible-playbook -i "18.236.75.XXX," server-overlay.yml
sudo logrotate -v -f /etc/logrotate.d/apache2 to force the logs to go into the s3 bucket.'

By default, the server_overlay playbook assumes the credentials are stored in the home directory:
`var_s3_push_credentials: "~/.s3cfg"`

A minimal s3cfg file looks like so: Note the keys differ from aws cli config file
[default]
access_key = XXXX
secret_key = YYYY

Tested using MacOs:
ansible 2.7.0 and ansible 2.1.0
python version = 2.7.14

EC2 instance specs:
VERSION="14.04.6 LTS, Trusty Tahr"
Python 2.7.6
python3 --version: Python 3.4.
s3cmd --version: s3cmd version 2.1.0

### CODE REVIEW

**Comment by abessiari** [comment]
@jamesaoverton 
CC: @kltm 

This PR is passes travis. :-)  The only difference is that this one is based out of master. Looks like the other PR is "out of touch" with the master branch. 
Please advise. I am also not able to add reviewers ...
Thanks.

**Comment by jamesaoverton** [comment]
I haven't tested this yet but it looks good over all. I'm not clear on the workflow for the credentials -- can you describe that please?

**Comment by abessiari** [comment]
Hi.

My understanding is that Seth will give you the credentials to access the
s3 bucket.
The server overlay script tests access to the s3 bucket and would fail if
not able to list
the contents of the bucket.  Let me know if you want me to document this
and where?

By default, the server_overlay playbook assumes the credentials are stored
in the home directory:
     var_s3_push_credentials: "~/.s3cfg"

A minimal s3cfg file looks like so:
# Note the keys differ from aws cli config file

[default]

access_key = XXXX

secret_key = YYYY

Thanks.
aes

**Comment by kltm** [comment]
@jamesaoverton If you are still a Signal user, our last interaction was credentials that should work for the bucket. If you no longer have access to the previous conversation, I can resend them.

**Pull request closed without merging**
