### PR TITLE
Create ontoneo.yml

### PR DESCRIPTION
**Pull request by FernandaFarinelli**
Pleases,

Create an entry for ontoneo in your purl registry according to ontoneo.yml file.

Thanks

Fernanda

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Almost there. Try `base_url: /obo/ontoneo`

**Comment by jamesaoverton** [comment]
Sorry that you're having trouble with this. I'm happy to fix it.

**Comment by FernandaFarinelli** [comment]
@jamesaoverton Could you help me?

**Comment by jamesaoverton** [comment]
No problem. I have a meeting right now, but I'll fix it after that.

**Comment by FernandaFarinelli** [comment]
I took out the entries and it passed.
I'd like to know what's wrong with my entries.

**Comment by jamesaoverton** [comment]
The PURL config is fixed. Sorry for the hassle.

I think there are some problems that should be resolved before merging. I'll follow up by email.

**Comment by jamesaoverton** [comment]
Unfortunately the imports still won't work because the file names do not have the same case. For example, the import <https://raw.githubusercontent.com/ontoneo-project/Ontoneo/master/import/uberon_import.owl> does not resolve to a file. The file in your GitHub repository is called `UBERON_import.owl`.

**Comment by FernandaFarinelli** [comment]
Ok
I'll check it.

**Comment by FernandaFarinelli** [comment]
@jamesaoverton, @cmungall and @mcourtot 

Please,

Let me know if I need to fix anything or if some improvement is needed.

Thank you for every help that all of you gave me.

**Comment by jamesaoverton** [comment]
All my concerns have been addresses, so I'll merge now.

- https://github.com/ontoneo-project/Ontoneo/issues/14
- https://github.com/ontoneo-project/Ontoneo/issues/15

**Pull request merged**
