### PR TITLE
Update ncit.yml

### PR DESCRIPTION
**Pull request by matentzn**
Related to https://github.com/NCI-Thesaurus/thesaurus-obo-edition/releases/tag/v2022-08-19

### CODE REVIEW

**Comment by matentzn** [comment]
@balhoff please review.

https://github.com/NCI-Thesaurus/thesaurus-obo-edition/releases/tag/v2022-08-19

Related to https://github.com/NCI-Thesaurus/thesaurus-obo-edition/pull/81

**Review by balhoff — APPROVED** [review]

**Comment by balhoff** [comment]
Thanks!

**Review by jamesaoverton — CHANGES_REQUESTED** [review]
Looks good to me. You can merge, or let me know and I'll do it.

**Review by jamesaoverton — APPROVED** [review]

**Comment by jamesaoverton** [comment]
(Accidentally closed this, sorry!)

**Pull request merged**
