### PR TITLE
Update obib.yml

### PR DESCRIPTION
**Pull request by jmwhorton**
OBIB repository has changed from biobanking/ontology to biobanking/biobanking.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Looks good to me. I'll wait for @zhengj2007 or @cstoeckert to approve and then merge.

**Comment by zhengj2007** [comment]
The merge was decided by OBIB group. I am good with it. @jamesaoverton Thanks for checking.

**Review by zhengj2007 — APPROVED** [review]

**Comment by matentzn** [comment]
@zhengj2007 can you also update the GitHub tracker in the metadata?

**Comment by zhengj2007** [comment]
@matentzn The link of GitHub tracker stay same. So, we don't need to change.

**Comment by matentzn** [comment]
Thanks!

**Pull request merged**
