### PR TITLE
Remove extra PR products

### PR DESCRIPTION
**Pull request by jamesaoverton**
See discussion on #420

### CODE REVIEW

**Comment by jamesaoverton** [comment]
These extra products are not needed by PR. They were only added because of confusion over the meaning of `products`. That's entirely my fault.

We need an automated check for this rule. This is the only exception that I'm aware of. Life will be easier if we remove the exception, and sooner is better.

Ok @nataled ?

**Comment by nataled** [comment]
That is fine. Bear in mind that we DO have such files, but the PURL is incorrect. I presume that would be handled somewhere below, by 'exact' or something.

**Comment by nataled** [comment]
Any idea why PRO PURLs for individual terms still work? The part of the PURL yaml for these is missing. I know that the old purl server (before there was purl.obolibrary.org) had been set up and probably still works. Maybe there is failover to that server instead?

**Comment by jamesaoverton** [comment]
Im not sure what you mean. PRs just show the changes. The current version of `pr.yml` on the `master` branch has everything: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/pr.yml

**Comment by cmungall** [comment]
@nataled it's generic, no need to register terms

**Comment by nataled** [comment]
So if I needed to specify a different destination, how would I do that? It used to be in this file, as far as I remember.

**Comment by nataled** [comment]
I mean there was a regex to do it.

**Pull request merged**
