### PR TITLE
Redirect DUO releases/ to list of releases

### PR DESCRIPTION
**Pull request by jamesaoverton**

### CODE REVIEW

**Review by matentzn — COMMENTED** [review]
I know this is what Melanie said, but isn't what she really wants:

```
https://github.com/EBISPOT/DUO/releases/download/v
```

?

**Comment by mcourtot** [comment]
I think @jamesaoverton has it right - sorry if I was unclear. I'd like to send to https://github.com/EBISPOT/DUO/releases so that users can see the list of all dated releases.

**Comment by matentzn** [comment]
Note though that if you do that, your version iris will not resolve!

**Comment by matentzn** [comment]
This main purpose of this redirect is so that you can use http://purl.obolibrary.org/obo/duo/releases/2020-02-03/duo.owl to obtain the right DUO version (OBO versioning principle).

**Comment by matentzn** [comment]
(in any case I can see now the `exact`... so my comments pertain to the other, the `prefix` entry.

**Comment by jamesaoverton** [comment]
@matentzn These are working for me http://purl.obolibrary.org/obo/duo/releases/2017-10-16/duo.owl redirects to a valid OWL file https://raw.githubusercontent.com/EBISPOT/DUO/v2017-10-16/duo.owl

The Travis check failed because my tests aren't quite clever enough. I'll fix that and merge.

**Comment by matentzn** [comment]
Great! Didnt know that that works as well!

**Pull request merged**
