### PR TITLE
Update ontoneo.yml

### PR DESCRIPTION
**Pull request by FernandaFarinelli**
This is an update related to request  "New version of Ontoneo #720".

### CODE REVIEW

**Comment by jamesaoverton** [comment]
It's important that PURLs be *permanent* identifiers. In this PR the three dated release PURLs are being dropped. These can be redirected to "version_X.Y" but they should not be dropped.

**Comment by FernandaFarinelli** [comment]
I'll check this.
Thanks.

**Comment by FernandaFarinelli** [comment]
@jamesaoverton I made updates on my ontoneo.yml.

**Comment by jamesaoverton** [comment]
Closing in favour of #739

**Pull request closed without merging**
