### PR TITLE
Update iao.yml

### PR DESCRIPTION
**Pull request by alanruttenberg**
Did some cleanup, reordering, section labeling. The current version is confusing as it still points at google code. Need to talk to Jie.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Thanks Alan. Do want to merge this version or wait? I can take a closer look tomorrow.

**Comment by jamesaoverton** [comment]
I took a close look at the diff. It's much easier to find the PURLs you want in this version. Thanks again.

The final "g" got lost from this replacement:

    - exact: /bfo2-transitional/notes
      replacement: https://docs.google.com/document/d/1CRLrqYyq9s2xaf3zT0mae190ZFDTWJnflgLEtY2Rf8g/edit?usp=sharin

As far as I can tell, these PURLs will no longer resolve:

    - exact: /dev/iao-dev.owl		
      replacement: http://information-artifact-ontology.googlecode.com/svn/trunk/src/ontology/iao-dev.owl

    - exact: /dev/owl2bits.owl		
      replacement: http://information-artifact-ontology.googlecode.com/svn/trunk/src/ontology/iao-owl2.owl

    - exact: /bfo-transitional/notes
      replacement: https://docs.google.com/document/d/1CRLrqYyq9s2xaf3zT0mae190ZFDTWJnflgLEtY2Rf8g/edit?usp=sharing

**Comment by cmungall** [comment]
Should we close this PR now we have #186?

**Comment by jamesaoverton** [comment]
@alanruttenberg did extensive cleanup of `iao.yml` in a1ab80c2f7d3ccf951e2b6636b1a973ef51fdaeb, making this PR unnecessary.

**Pull request closed without merging**
