### PR TITLE
Update DOID products to GitHub

### PR DESCRIPTION
**Pull request by jamesaoverton**
This is James resubmitting #244

Update to resolve directly to github to avoid berkeley server

For background, see https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/190

DO NOT MERGE YET: wait for @elviram to give the +1

### CODE REVIEW

**Comment by cmungall** [comment]
Looks sensible to me

**Comment by jamesaoverton** [comment]
@elviram I'm trying to clean up old PRs. Do you want the main DOID PURLs to point directly to GitHub?

**Comment by elviram** [comment]
@jamesaoverton Yes, makes sense.

**Comment by elviram** [comment]
I think there was a bit of miscommunication here. DO agreed for urls to point to the github repo. Not for the purl to point to the doid.obo. The DO still wants that purl to point to doid-non-classified.obo.
I apologize for the misunderstanding.

**Pull request merged**
