### PR TITLE
OARCS intial configuration

### PR DESCRIPTION
**Pull request by mjy**
This wasn't tested via the virtual machine route, it will need some tweaks.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Please use `base_url: /obo/oarcs`. Otherwise, commit 80bb03a looks good to me.

**Comment by mjy** [comment]
Updated in 6f5440d.  Do I need to close this and make another pull request?

**Comment by jamesaoverton** [comment]
The pull request was updated and the tests passed. It's ready to merge when the prefix request is finalized. Thanks.

**Comment by jamesaoverton** [comment]
Sorry, I dropped the ball on this.

I did not see any comments to the prefix request on the obo-discuss@lists.sourceforge.net mailing list (December 11, 2015), so we can go ahead and add these PURLs. Please update your pull request to match the `master` branch, and I will merge it.

**Comment by jamesaoverton** [comment]
You should also add OARCS to the OBO Registry, either via a [pull request](https://github.com/OBOFoundry/OBOFoundry.github.io#instructions-for-registry-curators) or a [new issue](https://github.com/OBOFoundry/OBOFoundry.github.io/issues).

**Comment by mjy** [comment]
Branch has been updated, and corresponding pull request submitted- https://github.com/OBOFoundry/OBOFoundry.github.io/pull/387

The paper describing the ontology will soon be in press with links out, would be good to get this resolved.

**Comment by jamesaoverton** [comment]
I just merged these changes as PR #305, and the OARCS PURLs are now live. I used a new PR simply to keep the repository history a little cleaner.

**Comment by mjy** [comment]
Thanks much James, I'm sorry for leaving this hanging for so long.

M

**Pull request closed without merging**
