### PR TITLE
add fobi.yml

### PR DESCRIPTION
**Pull request by pcastellanoescuder**

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Your file looks fine. It's not your fault that the Travis tests are failing. I'll have to look into that.

**Comment by pcastellanoescuder** [comment]
Thank you James!

Best wishes,

Pol Castellano Escuder

PhD Student
Statistics and Bioinformatics Research Group
Department of Genetics, Microbiology and Statistics. University of
Barcelona.
Facultat de Biologia - UB. Avda Diagonal, 643. 08028 Barcelona (Spain)
----
Biomarkers and Nutritional & Food Metabolomics Research Group
Department of Nutrition, Food Science and Gastronomy. University of
Barcelona.
Facultat de Farmàcia i Ciéncies de l'Alimentació - UB. Av. Joan XXIII, s/n.
08028 Barcelona (Spain)
Email: polcaes@gmail.com

**Comment by jamesaoverton** [comment]
I fixed the test in #600.

This file configures the PURLs for FOBI. You will also need to create an OBO Registry entry here with information about your project:

https://github.com/OBOFoundry/OBOFoundry.github.io/tree/master/ontology

I prefer to merge that one first, then this one.

**Comment by pcastellanoescuder** [comment]
Done! 

I've created a pull request in OBOFoundry.github.io with fobi.md file!

**Pull request merged**
