### PR TITLE
Switch all CHEBI URLs to HTTP

### PR DESCRIPTION
**Pull request by matentzn**
Travis [does not play well with FTP](https://docs.travis-ci.com/user/common-build-problems/#ftpsmtpother-protocol-do-not-work), so this just needed happening.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Hmm. We’ve been using FTP for 2.5 years or so. I’ve also run into some problems, but worked around them. Does everyone agree that switching to HTTP is a good idea?

**Comment by matentzn** [comment]
Your Travis jobs pulling chebi, do any of them work?

**Comment by jamesaoverton** [comment]
I guess I don’t have any.

Fetching with what? `robot`? `curl`?

**Comment by matentzn** [comment]
I think the problem is independent of the method but not sure. I tried robot and wget. Switching to http solved the issue!

**Comment by matentzn** [comment]
What are your worries switching to http?

**Comment by jamesaoverton** [comment]
Do you think Travis is just blocking FTP ports?

I'm worried that people have already written custom code to handle ChEBI FTP as a special case, and this will break their workflows. I'm not vetoing this change. I just want to hear a second opinion.

@cmungall What do you think?

**Comment by cmungall** [comment]
If people have already hard coded the ftp URLs they won't be affected. I
don't see any downsides or what can go wrong. And this will solve issues. I
been burned by weird behavior with ftp and owl api before

**Comment by jamesaoverton** [comment]
Ok. @matentzn please go ahead and merge.

**Comment by matentzn** [comment]
Thanks for the input! :)

**Pull request merged**
