### PR TITLE
Create fovt.yml

### PR DESCRIPTION
**Pull request by ramonawalls**
Create new config file for FOVT. Will ask to merge pull request after two week review period ends on 4/27.

### CODE REVIEW

**Comment by ramonawalls** [comment]
@jamesaoverton Thanks for fixing the capitalization. FYI, we took that file directly from what ODK produced, so probably that should be changed in ODK.

**Comment by matentzn** [comment]
Thanks will take care of that!

**Comment by matentzn** [comment]
Thanks @ramonawalls ODK fix is [done](https://github.com/INCATools/ontology-development-kit/pull/336).

**Comment by jamesaoverton** [comment]
This is ready to go, but I'd rather merge it after you add an OBO Registry entry to https://github.com/OBOFoundry/OBOFoundry.github.io/tree/master/ontology

**Comment by ramonawalls** [comment]
Thanks Nico and James. I just added the metadata file at
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1208.
------------------------------------------------------
Ramona L. Walls, Ph.D.
Assistant Research Professor, Bio5 Institute, University of Arizona
Part-time artist (https://www.instagram.com/omnivoresgratitutude/)

**Pull request merged**
