### PR TITLE
Create omo.yml

### PR DESCRIPTION
**Pull request by zhengj2007**
Add file for newly registered OBO metadata ontology (OMO)

### CODE REVIEW

**Comment by jamesaoverton** [comment]
If some IAO terms are going to redirect to OMO, then we need to carefully override the main term redirects like this https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/obo.yml#L22

If you give me a list of the overrides I can do that.

**Comment by zhengj2007** [comment]
@jamesaoverton Here is the list of terms. Thanks!
[termlist.txt](https://github.com/OBOFoundry/purl.obolibrary.org/files/4581560/termlist.txt)

**Comment by jamesaoverton** [comment]
#653 implements the required change. But in order for this to work, OMO needs to be on Ontobee.

**Comment by jamesaoverton** [comment]
I merged this into #653, so I'll close this PR.

**Comment by jamesaoverton** [comment]
After discussion in #653, let's move ahead with the original file, minus the IAO example term.

**Comment by jamesaoverton** [comment]
@zhengj2007 Is this ready to go?

**Pull request merged**
