### PR TITLE
genepio initial configuration

### PR DESCRIPTION
**Pull request by Public-Health-Bioinformatics**
One question: I can't quite tell if github's genpio/imports/ folder should be referred to below with /src/ or without?  (Same question for the foodon config too).  Thanks.

https://raw.githubusercontent.com/GenEpiO/genepio/master/src/imports/

### CODE REVIEW

**Comment by cmungall** [comment]
It's up to you how you organize the files in your github repo.

My own preference is to have at the top level:

```
foo.{obo,owl}
imports/
    bar_import.owl
    ...
subsets/
    foo-basic.obo
```

And have everything under `src` be source only

This is how the starter kits sets things up

**Comment by Public-Health-Bioinformatics** [comment]
Would be great to get this purl working soonish. :)

**Comment by jamesaoverton** [comment]
We're usually faster, but I was offline for a few days. Please wait 30 minutes then double check that the PURLs are working as you expect.

**Comment by Public-Health-Bioinformatics** [comment]
Looks like its all working, thanks!

**Pull request merged**
