### PR TITLE
Update dron.yml

### PR DESCRIPTION
**Pull request by matentzn**
@hoganwr maybe check this;

also, there are quite a few redirects in the dron config that are actually dead. Just FYI!

### CODE REVIEW

**Comment by matentzn** [comment]
Oops broke it :/ sorry on airplane now can't fix before tonight unless someone else.

**Comment by hoganwr** [comment]
I see these two errors, but deleting their associated entries could break
other things.  Is there a way to define prefixes/variables that don't have
to resolve that can then serve as the base of other entries?

2 failures (path, expected, actual):
273
<https://github.com/OBOFoundry/purl.obolibrary.org/runs/3320912362?check_suite_focus=true#step:9:273>
/obo/dron/releases/
274
<https://github.com/OBOFoundry/purl.obolibrary.org/runs/3320912362?check_suite_focus=true#step:9:274>
302 https://github.com/ufbmi/dron/releases/download/v
275
<https://github.com/OBOFoundry/purl.obolibrary.org/runs/3320912362?check_suite_focus=true#step:9:275>
302 https://github.com/ufbmi/dron/releases/latest/download/releases/
276
<https://github.com/OBOFoundry/purl.obolibrary.org/runs/3320912362?check_suite_focus=true#step:9:276>
/obo/dron/releases/2021-08-12/dron-base.obo
277
<https://github.com/OBOFoundry/purl.obolibrary.org/runs/3320912362?check_suite_focus=true#step:9:277>
302
https://github.com/ufbmi/dron/releases/download/v2021-08-12/dron-base.obo
278
<https://github.com/OBOFoundry/purl.obolibrary.org/runs/3320912362?check_suite_focus=true#step:9:278>
302
https://github.com/ufbmi/dron/releases/latest/download/releases/2021-08-12/dron-base.obo
279
<https://github.com/OBOFoundry/purl.obolibrary.org/runs/3320912362?check_suite_focus=true#step:9:279>For
more details, see their corresponding TSV files in 'tests/development'.
280
<https://github.com/OBOFoundry/purl.obolibrary.org/runs/3320912362?check_suite_focus=true#step:9:280>To
re-run tests for just those idspaces, use the script 'tools/test.py'.
281
<https://github.com/OBOFoundry/purl.obolibrary.org/runs/3320912362?check_suite_focus=true#step:9:281>make:
*** [Makefile:106: test] Error 1

**Comment by matentzn** [comment]
I think it was simply an ordering issue. Looks like its passing now.

**Comment by jamesaoverton** [comment]
This looks good to me. The PURL entries match in order, so the new entries at the end of the file will not override previous entries.

Should I merge this @hoganwr?

**Comment by hoganwr** [comment]
Yes go ahead and merge it, thanks!

**Pull request merged**
